import useSWR from 'swr'
import Layout from '../components/layout'
import Upload from '../components/upload'
import * as format from '../utils/format'


const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Import() {

  const { data, error } = useSWR('/api/yield-transfer', fetcher)
  let yieldTransfers
  if (error) {
    yieldTransfers = <div className="text-center pt-4">Failed to load data!</div>
  }
  else if (!data) {
    yieldTransfers = <div className="text-center pt-4">Loading data…</div>
  }
  else {
    yieldTransfers = (data.yieldTransfers.length == 0
      ? <></>
      : <table className="w-full">
        <caption>Imported Transactions</caption>
        <thead>
          <tr>
            <th>Completion date</th>
            <th>Account</th>
            <th>Asset</th>
            <th className="text-right">Amount</th>
          </tr>
          {data.yieldTransfers.map(transfer =>
            <tr key={transfer.date}>
              <td>{transfer.completionDate}</td>
              <td>{transfer.account}</td>
              <td>{transfer.asset.code}</td>
              <td className="text-right">{format.asCurrency(transfer.amount, transfer.asset.code, { hideSymbol: true, crypto: true, })}</td>
            </tr>
          )}
        </thead>
      </table>
    )
  }

  return (
    <Layout name="Import">
      <h2 className="mt-6 mb-2 font-bold border-b border-gray-700">Account Statement</h2>

      <p>Upload your account statement (can be generated in the SwissBorg app).</p>
      <Upload name="account-statement" url="/api/import-file" />

      <h2 className="mt-6 mb-2 font-bold border-b border-gray-700">Smart Yield Transfers</h2>

      <p>
        Smart Yield transfers (subscriptions & redemptions) are not made available in the account statement generated by SwissBorg.
        It is therefore necessary to add them seperately by uploading a separate Excel file.
      </p>
      <Upload name="yield-transfers" url="/api/import-file" />

      {yieldTransfers}
    </Layout>
  )
}
